<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Loader.Core\Loader.Core.csproj" />
    <ProjectReference Include="..\Loader.Lang\Loader.Lang.csproj" />
    <ProjectReference Include="..\Loader.Script\Loader.Script.csproj" />
  </ItemGroup>

</Project>
