<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Loader.Core\Loader.Core.csproj" />
    <ProjectReference Include="..\Loader.Lang\Loader.Lang.csproj" />
    <ProjectReference Include="..\Loader.Query\Loader.Query.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClickHouse.Client" Version="7.14.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.10" />
    <PackageReference Include="OpenTelemetry" Version="1.17.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
